#!/bin/bash

while :
do

  clear 
  echo
  echo "  mtk 专用boot，recovery解包工具"
  echo "        made by suda"
  echo
  echo "  1 - 解包boot"
  echo "  2 - 打包boot"
  echo "  3 - 解包recovery"
  echo "  4 - 打包recovery"
  echo "  x - 退出"
  echo
  echo -n " 请输入选择项: "
  read opt

    case $opt in
      1) cd boot;./../tools/unpack-MT65xx.pl boot.img;cd ..;;
      2) cd boot;./../tools/repack-MT65xx.pl -boot boot.img-kernel.img boot.img-ramdisk new_boot.img;cd ..;;
      3) cd recovery;./../tools/unpack-MT65xx.pl recovery.img;cd ..;;
      4) cd recovery;./../tools/repack-MT65xx.pl -recovery recovery.img-kernel.img recovery.img-ramdisk new_recovery.img;cd ..;;
      x) exit 1;;
    esac
done

